name = "vlo2g-app"
main = "src/index.ts"
compatibility_date = "2024-02-08"

# D1 Database Binding (Database ID is safe to keep here)
[[d1_databases]]
binding = "DB"
database_name = "blog"
database_id = "f5c53cee-e4f6-4c4c-a033-9fd20ca5716e"
